In [1]:
import numpy as np

In [8]:


matrix = np.array([
    [1,1,1,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,1]
])

print("Original matrix:\n", matrix)

n, m = matrix.shape
rowzero, colzero = False, False


for i in range(n):
    if matrix[i][0] == 0:
        colzero = True


for j in range(m):
    if matrix[0][j] == 0:
        rowzero = True

for i in range(1, n):
    for j in range(1, m):
        if matrix[i][j] == 0:
            matrix[i][0] = 0
            matrix[0][j] = 0


for i in range(1, n):
    for j in range(1, m):
        if matrix[i][0] == 0 or matrix[0][j] == 0:
            matrix[i][j] = 0


if rowzero:
    for j in range(m):
        matrix[0][j] = 0


if colzero:
    for i in range(n):
        matrix[i][0] = 0

print("Final matrix:\n", matrix)


Original matrix:
 [[1 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 1]]
Final matrix:
 [[1 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]]
