In [1]:
import numpy as np

In [8]:


matrix = np.array([
    [1,1,1,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,1]
])

print("Original matrix:\n", matrix)

n, m = matrix.shape
rowzero, colzero = False, False


for i in range(n):
    if matrix[i][0] == 0:
        colzero = True


for j in range(m):
    if matrix[0][j] == 0:
        rowzero = True

for i in range(1, n):
    for j in range(1, m):
        if matrix[i][j] == 0:
            matrix[i][0] = 0
            matrix[0][j] = 0


for i in range(1, n):
    for j in range(1, m):
        if matrix[i][0] == 0 or matrix[0][j] == 0:
            matrix[i][j] = 0


if rowzero:
    for j in range(m):
        matrix[0][j] = 0


if colzero:
    for i in range(n):
        matrix[i][0] = 0

print("Final matrix:\n", matrix)


Original matrix:
 [[1 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 1]]
Final matrix:
 [[1 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]]


In [ ]:
matrix=[[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
]
n=len(matrix)


#transpose 
for i in range(n):
    for j in range(i+1,n):
        matrix[i][j],matrix[j][i]=matrix[j][i],matrix[i][j]

#reverse matrix row
for i in range(n):
    matrix[i].reverse()

print(matrix)

[[13, 9, 5, 1], [14, 10, 6, 2], [15, 11, 7, 3], [16, 12, 8, 4]]


In [4]:
#spiral traversal of matrix

matrix=[[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
]

n=len(matrix)
m=len(matrix[0])
top,bottom=0,n-1
left,right=0,m-1
ans=[]

while(top<=bottom and left<=right):
    for i in range(left,right+1):
        ans.append(matrix[top][i])
    top+=1

    for i in range(top,bottom+1):
        ans.append(matrix[i][right])
    right-=1

    if top<=bottom:
        for i in range(right,left-1,-1):
            ans.append(matrix[bottom][i])
        bottom-=1

    if left<=right:
        for i in range(bottom,top-1,-1):
            ans.append(matrix[i][left])
        left+=1

print(ans)

[1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5, 6, 7, 11, 10]
